### ISSUE TITLE
Extensible Framework breaks ability to edit existing jokes 

### ISSUE THREAD

**Issue by paddypopeye** [spbooks/phpmysql6#1]
After the implementation of the framework the display of joketext in the textarea no longer works...
Editing actually inserts a new entry to the DB, and breaks the ability to edit existing jokes

**Comment by TRPB** [comment]
Where in the chapter are you up to, which is the closest sample code? There are times when things get changed and then fixed at a later point.

The samples `CMS-EntryPoint-Namespaces` and `CMS-EntryPoint-Namespaces-Router` both work as expected.

**Comment by paddypopeye** [comment]
hi... I am on Ch9 page 396, just beginning the "Autoloading and Namespaces", section. I think the relevant sample code is the CMS-EntryPoint-Framework. After a lot of troubleshooting, I became convinced I was doing something wrong. So, I cloned the sample code and ran it, same behaviour. But as you say it works in the later code samples, I will plough on so ... Thanks for the response.... Good Book  btw :-)

**Comment by TRPB** [comment]
Hmm, the sample CMS-EntryPoint-Framework is working. Can you paste the `edit` method from your `JokeController.php`?

```php
        public function edit() {
                if (isset($_POST['joke'])) {

                        $joke = $_POST['joke'];
                        $joke['jokedate'] = new DateTime();
                        $joke['authorId'] = 1;

                        $this->jokesTable->save($joke);

                        header('location: /joke/list');

                }
                else {

                        if (isset($_GET['id'])) {
                                $joke = $this->jokesTable->findById($_GET['id']);
                        }

                        $title = 'Edit joke';

                        return ['template' => 'editjoke.html.php',
                                        'title' => $title,
                                        'variables' => [
                                                        'joke' => $joke ?? null
                                                ]
                                        ];
                }
        }
```

Is what's in the sample. 

The issue could be in the list page if the joke's ID is not being correctly passed as a `$_GET` variable. When you click on the edit link, what is the URL in the address bar, if it's not something like `http://192.168.10.10/joke/edit?id=2` with the relevant variable and value, then the issue is probably in the list page when it creates the link.

**Comment by paddypopeye** [comment]
the url is correct,  I can see that the ID is being passed..here is the edit()....

```
public function edit(){
			
			if (isset($_POST['joke'])) {
					$date = new DateTime();
					$joke = $_POST['joke'];
					$joke['jokedate'] = $date->format('Y-m-d');
					$joke['authorid'] = 1;

					$this->jokesTable->save($joke);
					header('Location: /joke/list');
			}//end if 
			else{
				if (isset($_GET['id'])) {
					
					$joke = $this->jokesTable->findById($_GET['id']);
				}//end if 
				$title = "Edit Joke";
			}//end else
			return ['template' => 'editjoke.html.php',
					'title' => $title,
					'variables' => [
							'joke' => $joke ?? null]
					];
		}//end edit()
```

**Comment by TRPB** [comment]
Try changing it to this:

```php

public function edit(){
			
			if (isset($_POST['joke'])) {
					$date = new DateTime();
					$joke = $_POST['joke'];
					$joke['jokedate'] = $date->format('Y-m-d');
					$joke['authorid'] = 1;

					$this->jokesTable->save($joke);
					header('Location: /joke/list');
			}//end if 
			else{ 
                               var_dump($_GET);
				if (isset($_GET['id'])) {
					
					$joke = $this->jokesTable->findById($_GET['id']);
                                        var_dump($joke);
				}//end if 
				$title = "Edit Joke";
			}//end else
			return ['template' => 'editjoke.html.php',
					'title' => $title,
					'variables' => [
							'joke' => $joke ?? null]
					];
		}//end edit()
```

The two `var_dump`s will show you where the issue is. If the `$_GET` array doesn't have an `id` key, the issue is the link. If `var_dump($joke)` doesn't contain the joke then the issue is likely in the `DatabaseTable`'s `findById` method.

**Comment by paddypopeye** [comment]
What seems to be happening is that the $joke['joketext'] variable is not being passed when edit is clicked. For example if I replace` <?=$joke['joketext'] ?? ''?></textarea>..` with `<?=$joke['joketext'] ?? 'Some Text Here'?></textarea> `. The text is displayed. I will try the var_dump suggestion thanks

**Comment by paddypopeye** [comment]
the output of var_dump($_GET) is "array (size=0)
  empty"
here's the url
http://192.168.10.10/joke/edit?id=134

**Comment by TRPB** [comment]
That's very strange, it looks like the `$_GET` variable is not being created at all. Are you using the Homestead Improved box, another box, XAMPP or a different server?

**Comment by TRPB** [comment]
Can you change index.php to just 

```php
<?php
var_dump($_GET);
```

And visit the same URL http://192.168.10.10/joke/edit?id=134

If the `id` variable is set in `index.php` then something is emptying the `$_GET` variable later in the script. If it's empty there, then it has to be a server configuration issue which may not be quite so simple to fix.

**Comment by paddypopeye** [comment]
im using the homestead improved

**Comment by paddypopeye** [comment]
with var_dump in index.php

/home/vagrant/Code/Project/public/index.php:2:
array (size=0)

**Comment by TRPB** [comment]
That's odd. Have you made any changes to the configuration of the server by editing `/etc/nginx/sites-enabled/homestead.app` on the virtual machine?

Can you try changing the `var_dump` to print `$_SERVER` instead of `$_GET` and paste the output?

**Comment by paddypopeye** [comment]
Changing the try_files in /etc/nginx/sites-enables/homestead.app    to...

try_files $uri $uri/ /index.php?$query_string;

working now !! :-)

**Comment by TRPB** [comment]
Glad you got it working!
