### ISSUE TITLE
final website

### ISSUE THREAD

**Issue by ghost** [spbooks/phpmysql6#10]
Hi Tom,

I tried to run final-website with this error:

![image](https://user-images.githubusercontent.com/32238390/44016573-1224fa9c-9f08-11e8-91b1-1f7786a80a3e.png)

my directory structure is localhost/ijdb6/Project/public/index.php

tried to fix with xdebug but to no avail

Thanks

**Comment by TRPB** [comment]
The URL you're using to visit the page is wrong in the screenshot you have `localhost/ijdb6/Project/public/ijdb6/Project/public/index.php`

If you're using apache you'll also need the `.htaccess` file supplied in chapter 9.

**Comment by ghost** [comment]
hi Tom, thanks a lot for the reply
my mistake. after the `.htaccess` file in place, the URL no longer redirect to `localhost/ijdb6/Project/public/ijdb6/Project/public/index.php` and go straight to `localhost/ijdb6/Project/public/index.php` but still wont get thru with this error (the other samples are just fine)
![image](https://user-images.githubusercontent.com/32238390/44049270-324ab182-9f66-11e8-80ca-2f62746a58f1.png)

**Comment by ghost** [comment]
the sample codes for final-website i run came straight from github repo

![image](https://user-images.githubusercontent.com/32238390/44051945-d52d36fc-9f6d-11e8-9e8e-4e8374038bd9.png)

![image](https://user-images.githubusercontent.com/32238390/44052023-0d614d92-9f6e-11e8-9a72-74104a86e117.png)

![image](https://user-images.githubusercontent.com/32238390/44052047-246891b2-9f6e-11e8-8e33-0b66479ef674.png)

![image](https://user-images.githubusercontent.com/32238390/44052189-8118c80a-9f6e-11e8-8380-6c17066f2bd1.png)

after that fatal error then the browsers' url redirects to `http://localhost/ijdb6/Project/public/ijdb6/project/public/index.php`

I renamed the .htaccess file because with this file in place, xdebug wont start

**Comment by TRPB** [comment]
You're going to need to enable PHP's error reporting in php.ini, a 500 error is generally a placeholder that's displayed when real errors are turned off.

**Comment by ghost** [comment]
error reporting in php.ini is enable
maybe 500 errors can be due to syntax errors in a .htaccess file ?

**Comment by TRPB** [comment]
You can take a look at the apache error log to see if it gives any insight into the issue.

**Comment by ghost** [comment]
this is from the log..
also EntryPoint.php line 47 contains `$controler->$action()`

![image](https://user-images.githubusercontent.com/32238390/44154135-99637cec-a0dc-11e8-8a13-73156c57752e.png)

**Comment by TRPB** [comment]
Make sure you have PHP Error reporting turned on, you should see those kind of errors in the browser.

In any recent PHP version `$obj->$method()` is valid, what PHP version are you using?

As I mentioned at the beginning of the book you are better off using a virtual machine to do your development rather than wamp/xmapp. 

However, the errors below that do indicate an issue with your htaccess file. 

edit: Here's a brief introduction to .htaccess https://www.sitepoint.com/apache-mod_rewrite-examples/ it's not covered in the book because nginx is increasingly becoming a more popular sever and htaccess is apache specific.

**Comment by ghost** [comment]
im using php 7.2.8

yea, im thinking downloading the vm

yes, all errors are displaying on browser. specific to this sample no error displayed. not even get pass thru the wrong url. seems like xdebug get blocked by file .htaccess

**Comment by ghost** [comment]
thanks a lot Tom!

i think i will just reading your book till i meet its back cover and walk the extra miles to apache mod_rewrite and see what i can work out with this particular apache server module

you wrote a very good book, indeed, Tom!

thank you
