### ISSUE TITLE
permissions field in Author entity class is missing

### ISSUE THREAD

**Issue by NarniaT** [spbooks/phpmysql6#13]
The method hasPermission (in Author class) uses `$this->permissions` but the field isn't defined in the class.
(Also I wonder whether the line `$joke['jokedate'] = new \DateTime();` in the saveEdit method inside the Joke controller is not violating the separation of concerns principle and the [awesome] explanations of the book about why we use an ORM? Here, if I'm not mistaken, we're directly referring to an implementation detail of our jokes table-which is the field name "jokedate".)

**Comment by chasinglucid** [comment]
Also, the sample codeis missing the functionality of hasPermission.

**Comment by TRPB** [comment]
> (Also I wonder whether the line $joke['jokedate'] = new \DateTime(); in the saveEdit method inside the Joke controller is not violating the separation of concerns principle and the [awesome] explanations of the book about why we use an ORM? Here, if I'm not mistaken, we're directly referring to an implementation detail of our jokes table-which is the field name "jokedate".)

The same could be said any time the details of the joke are printed. `echo $joke['id']` or `echo $joke['joketext']`. It's really an issue of knowing only a shallow depth. When you write `echo $joke['id']` or `$joke['jokedate'] = new \DateTime();` you are assuming knowledge of the structure of the `$joke` array but you do not know (a) where the data came from or (b) what is going to be done with it after it's set.

Behind the scenes whatever is dealing with the `$joke` variable may or may not be writing it to a database table. After you've written `$joke['jokedate'] = new \DateTime();` it's up to whatever handles `$joke` to decide what to do with it. Defining `jokedate` alone requires no more knowledge than *whatever* is dealing with the `$joke` array is expecting a `jokedate` key set. It might save to a database, it might save to a CSV, it might not do anything.

The single concern is creating the `joke` array in the required format.

I'll take a look at the sample code shortly, can you let me know which branch it is you are looking at?

**Comment by mojtabaavdev** [comment]
Thanks Tom. Sure. It's the full website branch.

**Comment by NarniaT** [comment]
Thanks Tom. Sure. It's in the full-website branch.
