### ISSUE TITLE
Chapter 7 updateJoke function error

### ISSUE THREAD

**Issue by ghost** [spbooks/phpmysql6#18]
The error (from Intellij IDEA) says SET without WHERE clause....etc. Why isn't the rest of the query visible to PHP?
Here is the code which causes error:

function updateJoke($pdo, $fields) {
    **$query = ' UPDATE `joke` SET ';**  <--------"Reference or Select expected"

    foreach ($fields as $key => $value) {
        $query .= '`' . $key . '` = :' .$key . ',';
    }

    $query = rtrim($query, ',');

    $query .= ' WHERE `id` = :primaryKey';

**Comment by TRPB** [comment]
Because intellij isn't intelligent enough to realise that the query is built from different strings. Ignore it and run the code.

**Comment by bobate** [comment]
@StewieAndro 
Are you still working on this website framework? I'm almost a year behind you and having mixed results, looking for some guidance from someone who may have figured it all out, or can plod along with me.  I've been working on it about two months at this point.
I keep running into walls, taking a day to a week to resolve the problems. I had it more or less on track up thru categories, but now in Permissions I'm at a wall again. 
Would you have time and patience to respond to problems I would send you?
Thanks
Nate

**Comment by sakayaraj2000** [comment]
In the book at Chapter 7 and on the question you have asked with the code snippet provided is the following:
> foreach ($fields as $key => $value) {
>     $query .= '`' . $key . '` = :' .$key . ',';

The error is on the second line.
the second line should be as follows:

$query .= '`' . $key . '` = :' .$value . ',';

Please note that the second variable should be the $value variable and NOT the $key variable.

Please let me know if this has solved your issue.

**Comment by TRPB** [comment]
The book is correct, it should be ` $query .= '' . $key . ' = :' .$key . ',';` because the query generated will be `jokteText = :jokeText, jokedate = :jokedate`, etc.
