### ISSUE TITLE
Functions to allow Editing joke categories breaks several features of the website, and also issues with logging out.....

### ISSUE THREAD

**Issue by paddypopeye** [spbooks/phpmysql6#2]
After downloading the sample code, am receiving multiple errors

1)  Notice: Undefined variable: categories in /home/vagrant/Code/Project/templates/jokes.html.php on line 4
2) Warning: Invalid argument supplied for foreach() in /home/vagrant/Code/Project/templates/jokes.html.php on line 4
3) Notice: Undefined variable: user in /home/vagrant/Code/Project/templates/jokes.html.php on line 29

***** LOGGING OUT*****
The logout.html.php is displayed if a logout attempt  is made, and the link changes to "Login". 
But the session is not destroyed, is still possible to navigate to edit jokes. And as soon as you navigate away from the logout page, the link returns to "Logout". 

******EDIT ****

Logging out now working ... Added session_destroy(), but other errors persist(help would be appreciated)

public function logout() {
		unset($_SESSION);
		session_destroy();
		return ['template' => 'logout.html.php', 'title' => 'You have been logged out'];
	}

**Comment by paddypopeye** [comment]
The inclusion of "$jokeEntity->clearCategories();" to the savedit() breaks the function.... 
'Notice: Undefined variable: loggedIn in /home/vagrant/Code/Project/templates/layout.html.php on line ...
MySQL server version for the right syntax to use near 'jokeid= NULL'

**Comment by TRPB** [comment]
Hi @paddypopeye since you closed the issue did you manage to resolve it?
