### ISSUE TITLE
Where can I download database.sql named on chapter 4

### ISSUE THREAD

**Issue by PedroFumero** [spbooks/phpmysql6#20]
Where can I download the files that he talk on this capture? 

![Question](https://sjc1.discourse-cdn.com/sitepoint/community/uploads/default/original/3X/a/c/ac7ffc20aae12bcd26ae89e4d6a1e5ddcf10dd17.png)

**Comment by simonmackie** [comment]
Hi @PedroFumero, you should follow the instructions covered in Appendix A
