### ISSUE TITLE
Chapter 9 Breaks my code

### ISSUE THREAD

**Issue by squirz96** [spbooks/phpmysql6#7]
Here are few errors when I try running "index.php" : 
PHP Fatal error:  Uncaught TypeError: Argument 2 passed to Ninja\EntryPoint::__construct() must be of the type string, null given, called in /srv/http/ph/examples/index.php on line 6 and defined in /srv/http/ph/classes/Ninja/EntryPoint.php:9
Stack trace:
#0 /srv/http/ph/examples/index.php(6): Ninja\EntryPoint->__construct('', NULL, Object(Ijdb\IjdbRoutes))
#1 {main}
  thrown in /srv/http/ph/classes/Ninja/EntryPoint.php on line 9

When I got the book, I already got my LAMP server running, ph is just directory for php projects. Also, I am using php storm IDE

**Comment by TRPB** [comment]
can you let me know which branch, page or example you are using?

**Comment by squirz96** [comment]
The last branch I used was: 
CMS-EntryPoint-Interface

**Comment by squirz96** [comment]
I kinda solved this, by using vagrant. Altrough, I am interested why default LAMP server gives me an error

**Comment by TRPB** [comment]
It shouldn't make a difference, on apache can you run `var_dump($_SERVER)`.

Your error was on this line:

```
	$entryPoint = new \Ninja\EntryPoint($route, $_SERVER['REQUEST_METHOD'], new \Ijdb\IjdbRoutes());
```

So if for some reason `$_SERVER` is not set correctly then it will not work. However, apache should set the `$_SERVER` variable correctly.

**Comment by squirz96** [comment]
https://pastebin.com/a8CiEf0j

**Comment by TRPB** [comment]
Strange, `$_SERVER['REQUEST_URI']` and `REQUEST_METHOD` are not set which is what's causing the issue.

It looks like PHP is being run from the command line rather than via a web server as $_SERVER['argv'] is set. How do you have apache configured to run PHP? There's a similar question here  https://stackoverflow.com/questions/35137278/request-uri-set-or-not-set but no answers.

**Comment by squirz96** [comment]
I am running 7.2 version of PHP.  By the way, those errors that where mentioned in the beginning is not displayed when I try to access from webserver.
When I try to access from webserver I get http 500 error.

**Comment by TRPB** [comment]
You will get the errors in post 1 if you run from the command line. You must run it through a web server so that REQUEST_URI and REQUEST_METHOD are set.

If you are getting 500 errors, you will need to configure PHP and apache to display errors rather than the generic error page. You will then see a specific error message.

**Comment by squirz96** [comment]
This is what I get with enabled function to display specific errors:
Notice: Undefined index: ph/examples/ in /srv/http/ph/classes/Ninja/EntryPoint.php on line 35

Notice: Undefined index: ph/examples/ in /srv/http/ph/classes/Ninja/EntryPoint.php on line 36

Fatal error: Uncaught Error: Method name must be a string in /srv/http/ph/classes/Ninja/EntryPoint.php:38 Stack trace: #0 /srv/http/ph/examples/index.php(8): Ninja\EntryPoint->run() #1 {main} thrown in /srv/http/ph/classes/Ninja/EntryPoint.php on line 38

**Comment by squirz96** [comment]
`<?php
namespace Ninja;

class EntryPoint {
    private $route;
    private $method;
    private $routes;
    public function __construct(string $route, string $method, \Ninja\Routes $routes) {
        $this->route = $route;
        $this->routes = $routes;
        $this->method = $method;
        $this->checkUrl();
    }

    private function checkUrl() {
        if ($this->route !== strtolower($this->route)) {
            http_response_code(301);
            header('location: ' . strtolower($this->route));
        }
    }

    private function loadTemplate($templateFileName, $variables = []) {
        extract($variables);

        ob_start();
        include  __DIR__ . '/../../templates/' . $templateFileName;

        return ob_get_clean();
    }

    public function run() {

        $routes = $this->routes->getRoutes();

        $controller = $routes[$this->route][$this->method]['controller'];
        $action = $routes[$this->route][$this->method]['action'];

        $page = $controller->$action();

        $title = $page['title'];

        if (isset($page['variables'])) {
            $output = $this->loadTemplate($page['template'], $page['variables']);
        }
        else {
            $output = $this->loadTemplate($page['template']);
        }

        include  __DIR__ . '/../../templates/layout.html.php';
    }
}`

This is my  EntryPoint.php file

**Comment by TRPB** [comment]
Is that when you are accessing via a web server rather than command line? If so, try using `var_dump` to display `$_SERVER` on the web page. Are `REQUEST_URI` and `REQUEST_METHOD` set when accessing the page via a web browser?

**Comment by TRPB** [comment]
Actually if it's getting to entrypoint, perhaps not. Check that your `$routes` variable is set correctly. Compare the contents of `$_SERVER['REQUEST_URI']`  to the array keys in your `$routes` variable.

**Comment by squirz96** [comment]
Result of var_dump: https://pastebin.com/2w2KQ0sJ
`$routes = [
            'joke/edit' => [
                'POST' => [
                    'controller' => $jokeController,
                    'action' => 'saveEdit'
                ],
                'GET' => [
                    'controller' => $jokeController,
                    'action' => 'edit'
                ]

            ],
            'joke/delete' => [
                'POST' => [
                    'controller' => $jokeController,
                    'action' => 'delete'
                ]
            ],
            'joke/list' => [
                'GET' => [
                    'controller' => $jokeController,
                    'action' => 'list'
                ]
            ],
            '' => [
                'GET' => [
                    'controller' => $jokeController,
                    'action' => 'home'
                ]
            ]
        ];`

**Comment by TRPB** [comment]
The problem is that you have the scripts in a subdirectory.

```
["REQUEST_URI"]=> string(13) "/ph/examples/"
```

You'll need to adjust all your routes accordingly.

**Comment by squirz96** [comment]
/ph/examples is directory of index.php file

**Comment by TRPB** [comment]
Which means your URLs are, for example, `ph/examples/joke/delete` instead of 'joke/delete`and you'll need to adjust the routes with this URL.

**Comment by squirz96** [comment]
Changed to:

`   $routes = [
            'ph/examples/joke/edit' => [
                'POST' => [
                    'controller' => $jokeController,
                    'action' => 'saveEdit'
                ],
                'GET' => [
                    'controller' => $jokeController,
                    'action' => 'edit'
                ]

            ],
            'ph/examples/joke/delete' => [
                'POST' => [
                    'controller' => $jokeController,
                    'action' => 'delete'
                ]
            ],
            'ph/examples/joke/list' => [
                'GET' => [
                    'controller' => $jokeController,
                    'action' => 'list'
                ]
            ],
            '' => [
                'GET' => [
                    'controller' => $jokeController,
                    'action' => 'home'
                ]
            ]
        ];`

Same problem

**Comment by TRPB** [comment]
You'll need to do the same for the home page.

**Comment by squirz96** [comment]
`<?php
try {
    include __DIR__ . '/../includes/autoload.php';

    $route = ltrim(strtok($_SERVER['REQUEST_URI'], '?'), '/');
    var_dump($_SERVER);
    $entryPoint = new \Ninja\EntryPoint($route, $_SERVER['REQUEST_METHOD'], new \Ijdb\IjdbRoutes());
    $entryPoint->run();
}
catch (PDOException $e) {
    $title = 'An error has occurred';
    $output = 'Database error: ' . $e->getMessage() . ' in ' .
        $e->getFile() . ':' . $e->getLine();
    include  __DIR__ . '/../templates/layout.html.php';
}`

Here are no routers set

**Comment by squirz96** [comment]
`<li><a href="/ph/examples">Home</a></li>
        <li><a href="/ph/examples/joke/list">Jokes List</a></li>
        <li><a href="ph/examples/joke/edit">Add a new Joke</a></li>`

**Comment by TRPB** [comment]
Are you getting any error messages?

**Comment by squirz96** [comment]
Yep same

**Comment by TRPB** [comment]
But did you change the $routes array for the home page entry?

**Comment by squirz96** [comment]
I am going to try something

**Comment by squirz96** [comment]
Ha it works when I change default location of a server. However, there is a little problem.

**Comment by squirz96** [comment]
The problem is that when I try to open any link for example /jokes/edit.  It gives page not found error

**Comment by TRPB** [comment]
That's because your URLs aren't `/joke/edit` they are `/ph/examples/joke/edit`. 

Generally speaking, you're better off running each website at the top level. If you already have code running in the top level you should configure apache vhosts so that you can have http://project1.local/, http://project2.local/ etc hosting different websites.

**Comment by squirz96** [comment]
While I was waiting for a response to this problem I decided that I would use vagrant and now I am now ch 12 of a book.  I had copied my project folder aka my_project/Project to /srv/http location and configured apache so /srv/http/Project/public would become my new root direction for a server.  Aka when I visit 127.0.0.1 or my private ip address it goes straight to the /srv/http/Project/public/index.php displaying Home page of a website

**Comment by squirz96** [comment]
I will upload my project to my github account

**Comment by squirz96** [comment]
https://github.com/squirz96/PHPMYSQL here you are my current source code for a project

**Comment by TRPB** [comment]
Are you having an issue? Your last post implied you had fixed it. If you are using vagrant you will need to use the 192.168.10.10 address not 127.0.0.1.

**Comment by squirz96** [comment]
Everything is alright if I use vagrant, however if I use my local LAMP server I can only go to the homepage, all other pages are error not found.

**Comment by squirz96** [comment]
like /jokes/list ...etc

**Comment by squirz96** [comment]
So it doesn't work

**Comment by TRPB** [comment]
As I said, your urls are not `/joke/list` but `/ph/examples/joke/list` so you'll need to amend every link. 

> That's because your URLs aren't /joke/edit they are /ph/examples/joke/edit.
>
> Generally speaking, you're better off running each website at the top level. If you already have code running in the top level you should configure apache vhosts so that you can have http://project1.local/, http://project2.local/ etc hosting different websites.

**Comment by squirz96** [comment]
Like I said I had changed my apache settings so my home page aka localhost would go  to /srv/http/Project/public.  I had copied my vagrant project to /srv/http

**Comment by squirz96** [comment]
Just look at my apache config file

**Comment by TRPB** [comment]
Did you create the .htaccess file as described in chapter 9? You need this for apache.

**Comment by squirz96** [comment]
Jeez thanks now it works.
